name: Naukri Automation CI

on:
  push:
    branches: [ "dipankar_infy_0.1" ]
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Create directories
        run: |
          mkdir -p target/{surefire-reports,screenshots,ExtentReports}
          mkdir -p logs

      - name: Build and Test
        env:
          CI: true
          CHROME_OPTIONS: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080 --remote-allow-origins=* --disable-notifications"
          JAVA_OPTS: "-Dwebdriver.http.factory=jdk-http-client"
        run: |
          mvn clean test -B \
          -Dwebdriver.http.factory=jdk-http-client \
          -Dwebdriver.chrome.whitelistedIps= \
          -Dselenium.browser.timeout=60000 \
          -Dselenium.page.load.timeout=60000 \
          -Dwebdriver.timeouts.implicitlywait=30000

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: |
            target/surefire-reports/
            target/screenshots/
            target/ExtentReports/
            target/ExtentReport.html
            logs/
          retention-days: 5

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots-${{ github.run_id }}
          path: target/screenshots/
          retention-days: 5

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3.11.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Naukri Automation - ${{ job.status }}
          to: dc954725@gmail.com
          from: GitHub Actions <noreply@github.com>
          body: |
            Job ${{ github.job }} completed with status: ${{ job.status }}
            
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            
            See run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: |
            target/ExtentReport.html
            target/surefire-reports/emailable-report.html