name: Run Naukri Automation Daily

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Run TestNG Tests
        run: |
          mvn clean test -DsuiteXmlFile=src/test/resources/TestNG/testng.xml
        env:
          SELENIUM_BROWSER: chrome
          CHROME_OPTIONS: --headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu
          JAVA_OPTS: -Dwebdriver.http.factory=jdk-http-client

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3.11.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Naukri Automation Result
          to: dc954725@gmail.com
          from: GitHub Action
          body: Naukri automation test execution completed
          attachments: target/surefire-reports/emailable-report.html